# Generated by Django 5.2 on 2025-07-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
