# Generated by Django 5.2 on 2025-07-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_chatsession_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyviolation",
            name="complaint_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policyviolation",
            name="incidents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policyviolation",
            name="policy_violations",
            field=models.TextField(blank=True, null=True),
        ),
    ]
