# Generated by Django 3.2.12 on 2025-07-15 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_policyviolation_complaint_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyviolation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='policyviolation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
