# Generated by Django 5.2.4 on 2025-08-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_convert_policyviolation_ids_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
