# Generated by Django 3.2.12 on 2025-08-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chatsession_gender_chatsession_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='nationality',
            new_name='industrial_sector',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='gender',
        ),
    ]
