# Generated by Django 5.2.4 on 2025-08-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_auto_20250803_2033"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="industrial_sector",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
