# Generated by Django 3.2.12 on 2025-08-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_chatsession_industrial_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='industrial_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
